2025-03-24 13:28:29 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:29.574349-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:29 - INFO - Received VoteRequest: term=-1, candidate_id=0, last_log_index=0, last_log_term=0
2025-03-24 13:28:30 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:30.577324-04:00"}"
>
2025-03-24 13:28:31 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:31.585581-04:00"}"
>
2025-03-24 13:28:32 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:32.590855-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:33 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:33.596469-04:00"}"
>
2025-03-24 13:28:34 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:34.601079-04:00"}"
>
2025-03-24 13:28:35 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:35.610194-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:36 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:36.61836-04:00"}"
>
2025-03-24 13:28:37 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:37.624889-04:00"}"
>
2025-03-24 13:28:38 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:38.631629-04:00"}"
>
2025-03-24 13:28:39 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:39.637751-04:00"}"
>
2025-03-24 13:28:40 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:40.639231-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:41 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:41.641543-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:42 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:42.64988-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:43 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:43.655925-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:44 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:44.662072-04:00"}"
>
2025-03-24 13:28:45 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:45.668847-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:46 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:46.677572-04:00"}"
>
2025-03-24 13:28:47 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:47.684566-04:00"}"
>
2025-03-24 13:28:48 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:48.687242-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:49 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:49.693314-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:50 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:50.697944-04:00"}"
>
2025-03-24 13:28:51 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:51.70227-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:52 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:52.711282-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:53 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:53.720422-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:54 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:54.721903-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:28:55 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:55.727096-04:00"}"
>
2025-03-24 13:28:56 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:56.734288-04:00"}"
>
2025-03-24 13:28:57 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:57.739817-04:00"}"
>
2025-03-24 13:28:58 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:28:58.746544-04:00"}"
>
2025-03-24 13:28:59 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:28:59.749861-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:00 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:00.752977-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:01 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:01.758075-04:00"}"
>
2025-03-24 13:29:02 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:02.765744-04:00"}"
>
2025-03-24 13:29:03 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:03.772067-04:00"}"
>
2025-03-24 13:29:04 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:04.77372-04:00"}"
>
2025-03-24 13:29:05 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:05.776256-04:00"}"
>
2025-03-24 13:29:06 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:06.782166-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:07 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:07.785015-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:08 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:08.788733-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:09 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:09.793426-04:00"}"
>
2025-03-24 13:29:10 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:10.797446-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:11 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:11.802118-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:12 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:12.80808-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:13 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:13.814295-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:14 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:14.818368-04:00"}"
>
2025-03-24 13:29:15 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:15.8313-04:00"}"
>
2025-03-24 13:29:16 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:16.834582-04:00"}"
>
2025-03-24 13:29:17 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:17.841454-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:18 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:18.846402-04:00"}"
>
2025-03-24 13:29:19 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:19.851728-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:20 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:20.860648-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:21 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:21.866776-04:00"}"
>
2025-03-24 13:29:22 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:22.872471-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:23 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:23.879924-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:24 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:24.882667-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:25 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:25.886847-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:26 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:26.894674-04:00"}"
>
2025-03-24 13:29:27 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:27.897668-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:28 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:28.902285-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:29 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:29.905539-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:30 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:30.910026-04:00"}"
>
2025-03-24 13:29:31 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:31.915882-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:29:32 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:32.923511-04:00"}"
>
2025-03-24 13:29:33 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:29:33.931048-04:00"}"
>
2025-03-24 13:29:34 - ERROR - Error connecting to 127.0.0.1:50000: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:29:34.935505-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50000: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:32:36 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:32:36.988706-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:32:37 - INFO - Received VoteRequest: term=-1, candidate_id=0, last_log_index=0, last_log_term=0
2025-03-24 13:32:37 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:32:37.994666-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:32:38 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:32:38.997288-04:00"}"
>
2025-03-24 13:32:40 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:32:40.004941-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:32:41 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:32:41.01337-04:00"}"
>
2025-03-24 13:32:42 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:32:42.019925-04:00"}"
>
2025-03-24 13:32:43 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:32:43.026363-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:35:37 - INFO - Connected to 127.0.0.1:50005 with response: 
2025-03-24 13:35:37 - INFO - Connected to 127.0.0.1:50001 with response: 
2025-03-24 13:35:37 - ERROR - Error connecting to <grpc._server._Server object at 0x103bd1ad0>: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:35:37.681401-04:00"}"
>
2025-03-24 13:35:38 - INFO - Received VoteRequest: term=-1, candidate_id=0, last_log_index=0, last_log_term=0
2025-03-24 13:35:38 - INFO - Received VoteRequest: term=-1, candidate_id=0, last_log_index=0, last_log_term=0
2025-03-24 13:35:38 - ERROR - Error connecting to <grpc._server._Server object at 0x103bd1ad0>: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:35:38.687413-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:35:39 - ERROR - Error connecting to <grpc._server._Server object at 0x103bd1ad0>: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T13:35:39.694025-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 13:35:40 - INFO - Received VoteRequest: term=-1, candidate_id=0, last_log_index=0, last_log_term=0
2025-03-24 13:35:40 - INFO - Connected to 127.0.0.1:50003 with response: 
2025-03-24 13:35:40 - ERROR - Error connecting to <grpc._server._Server object at 0x103bd1ad0>: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50004: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50004: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T13:35:40.704262-04:00"}"
>
2025-03-24 13:35:41 - INFO - Received VoteRequest: term=-1, candidate_id=0, last_log_index=0, last_log_term=0
2025-03-24 13:35:41 - INFO - Connected to 127.0.0.1:50004 with response: 
2025-03-24 13:35:41 - INFO - Server started on port 50002
