2025-03-24 16:24:10 - INFO - Size of response: 80
2025-03-24 16:24:12 - INFO - Size of response: 80
2025-03-24 16:25:50 - INFO - Size of response: 80
2025-03-24 16:25:52 - INFO - Size of response: 80
2025-03-24 16:25:52 - INFO - Size of response: 80
2025-03-24 16:25:52 - INFO - Size of response: 80
2025-03-24 16:26:03 - INFO - Size of response: 80
2025-03-24 16:26:06 - INFO - Size of response: 80
2025-03-24 16:26:06 - INFO - Size of response: 80
2025-03-24 16:26:06 - INFO - Size of response: 80
2025-03-24 16:26:06 - INFO - Size of response: 80
2025-03-24 16:26:32 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50004 {created_time:"2025-03-24T16:26:32.902615-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-03-24 16:26:32 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50004 {created_time:"2025-03-24T16:26:32.902615-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-03-24 16:27:13 - INFO - Size of response: 80
2025-03-24 16:27:14 - INFO - Size of response: 80
2025-03-24 16:27:21 - INFO - Size of response: 80
2025-03-24 16:27:26 - INFO - Size of response: 80
2025-03-24 16:27:28 - INFO - Size of response: 80
2025-03-24 16:27:28 - INFO - Size of response: 80
2025-03-24 16:27:28 - INFO - Size of response: 80
2025-03-24 16:28:36 - INFO - Size of response: 80
2025-03-24 16:28:38 - INFO - Size of response: 80
2025-03-24 16:28:47 - INFO - Size of response: 80
2025-03-24 16:28:50 - INFO - Size of response: 80
2025-03-24 16:28:50 - INFO - Size of response: 80
2025-03-24 16:28:50 - INFO - Size of response: 80
2025-03-24 16:28:55 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50002 {created_time:"2025-03-24T16:28:55.161387-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-03-24 16:28:55 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50002 {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-03-24T16:28:55.161374-04:00"}"
>
2025-03-24 19:00:24 - INFO - Size of response: 80
2025-03-24 19:00:28 - INFO - Size of response: 80
2025-03-24 19:00:28 - INFO - Size of response: 80
2025-03-24 19:00:32 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50002 {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-03-24T19:00:32.540331-04:00"}"
>
2025-03-24 19:00:32 - ERROR - Error connecting to 127.0.0.1:50002: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:00:32.546303-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 19:00:35 - ERROR - Error connecting to 127.0.0.1:50002: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:00:35.93142-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 19:00:35 - ERROR - Unable to connect to any server.
2025-03-24 19:03:33 - INFO - Size of response: 80
2025-03-24 19:03:35 - INFO - Size of response: 80
2025-03-24 19:03:49 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50004 {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-03-24T19:03:49.167128-04:00"}"
>
2025-03-24 19:03:49 - ERROR - Error connecting to 127.0.0.1:50004: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50004: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50004: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T19:03:49.174477-04:00"}"
>
2025-03-24 19:03:59 - INFO - Deleting Account: nick
2025-03-24 19:04:00 - INFO - Deleting Account: nick
2025-03-24 19:04:00 - INFO - Deleting Account: nick
2025-03-24 19:04:00 - INFO - Deleting Account: nick
2025-03-24 19:04:00 - INFO - Deleting Account: nick
2025-03-24 19:04:16 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-03-24T19:04:16.386637-04:00"}"
>
2025-03-24 19:04:16 - ERROR - Error connecting to 127.0.0.1:50001: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50001: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T19:04:16.390511-04:00"}"
>
2025-03-24 19:04:16 - ERROR - Error connecting to 127.0.0.1:50004: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50004: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:04:16.395456-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50004: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 19:07:42 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:07:42.158491-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-03-24 19:07:42 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T19:07:42.160416-04:00"}"
>
2025-03-24 19:08:47 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-03-24T19:08:47.973715-04:00"}"
>
2025-03-24 19:08:47 - ERROR - Error connecting to 127.0.0.1:50002: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:08:47.979519-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 19:08:47 - ERROR - Unable to connect to any server.
2025-03-24 19:10:01 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-03-24T19:10:01.142999-04:00"}"
>
2025-03-24 19:10:01 - ERROR - Error connecting to 127.0.0.1:50005: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50005: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T19:10:01.145062-04:00"}"
>
2025-03-24 19:10:01 - ERROR - Unable to connect to any server.
2025-03-24 19:10:51 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Cancelling all calls", grpc_status:14, created_time:"2025-03-24T19:10:51.263735-04:00"}"
>
2025-03-24 19:10:52 - ERROR - Error connecting to 127.0.0.1:50003: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50003: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T19:10:52.27543-04:00"}"
>
2025-03-24 19:10:52 - ERROR - Unable to connect to any server.
2025-03-24 19:12:27 - ERROR - Error receiving response: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Cancelling all calls"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:12:27.382907-04:00", grpc_status:14, grpc_message:"Cancelling all calls"}"
>
2025-03-24 19:12:28 - ERROR - Error connecting to 127.0.0.1:50002: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:12:28.389348-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 19:12:28 - ERROR - Unable to connect to any server. Retries left: 3
2025-03-24 19:12:29 - ERROR - Error connecting to 127.0.0.1:50002: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-03-24T19:12:29.405047-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"}"
>
2025-03-24 19:12:29 - ERROR - Unable to connect to any server. Retries left: 2
2025-03-24 19:12:30 - ERROR - Error connecting to 127.0.0.1:50002: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50002: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-03-24T19:12:30.42103-04:00"}"
>
2025-03-24 19:12:30 - ERROR - Unable to connect to any server. Retries left: 1
